version: "3.3"

services:
  mongodb:
    image: mongo
    restart: "always"
    ports: ["27017:27017"]
    networks:
      - backend
    env_file:
      - ./config/db.env
  backend:
    depends_on:
      - mongodb
    build: ./Store-Manager-Back/
    ports: ["3000:3000"]
    restart: "always"
    networks:
      - backend
    volumes:
      - "./Store-Manager-Back:/app"
      - "/app/node_modules"
  # frontend:
  #   depends_on:
  #     - backend
  #   build: ./Store-Manager-Front/
  #   ports: ["4200:4200"]
  #   restart: "always"
  #   networks:
  #     - backend
  #   volumes:
  #     - "./Store-Manager-Front:/app"
  #     - "/app/node_modules"
networks:
  backend:
    driver: bridge
